version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/unofficial-wrfg
    steps:
      - checkout
      - run:
          name: Build
          command: script/deploy/build
      - run:
          name: Ship
          command: script/deploy/ship
workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
