---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/archives
  label: Archives
  create: all
  match: "**/*"
- type: directory
  path: content/programs
  label: Programs
  create: documents
  match: "**/*"
  templates:
  - program
- type: directory
  path: content/shows
  label: Shows
  create: documents
  match: "**/*"
  templates:
  - show
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
  templates:
  - page
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run build
