#!/bin/bash -e

# move into that directory
cd public/

# scaffold git repo, on branch `gh-pages`
git init
git checkout -b gh-pages
git remote add origin https://${GITHUB_TOKEN}@github.com/wrfg/wrfg.org.git

mkdir -p ~/.ssh
ssh-keyscan github.com >> ~/.ssh/known_hosts

git config --global user.email "jonathantrevorh+ci@gmail.com"
git config --global user.name "Jonathan Hunsucker (CI)"

# add all files
git add .

# commit
git commit -m "Build on `date`"

# push it up forcefully
git push -f --set-upstream origin gh-pages
